---
version: '3'

tasks:
  default:
    cmds:
      - echo "Hello World"
    silent: true

  build:
    deps:
      - clean
    cmds:
      - zensical build --clean

  run:
    deps:
      - clean
    aliases: [serve, server]
    cmds:
      - zensical serve

  clean:
    cmds:
      - rm -rf ./.cache 
      - rm -rf ./.venv
