---
name: Documentation

on:
  release:
    types: [published]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/configure-pages@v6
      - name: Inject Release Version into JS
        run: |
          NEW_VERSION="${{ github.ref_name }}"
          sed -i.bak -E "s/(const VERSION = \")[^\"]+(\";)/\1${NEW_VERSION}\2/" version.js
          rm version.js.bak
      - uses: actions/upload-pages-artifact@v5
        with:
          path: .
      - id: deployment
        uses: actions/deploy-pages@v5
